# Generated by Django 6.0 on 2025-12-27 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comment_bug_solution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugsolution',
            name='upvotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='upvoted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
