# Generated by Django 6.0 on 2025-12-27 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bugsolution_bug_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugsolution',
            name='bug_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='api.bugpost'),
        ),
    ]
