# Generated by Django 6.0 on 2025-12-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bugsolution_bug_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='tags', to='api.bugpost'),
        ),
    ]
