# Generated by Django 6.0 on 2025-12-31 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_bugsolution_upvotes_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='bug_solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='api.bugsolution'),
        ),
    ]
